### ISSUE TITLE
Run this cause PS Vita turn off

### ISSUE THREAD

**Issue by jasonkhoo87** [SKGleba/VitaDeploy#1]
I just install normal version that for vita shell.
After install, I run the app and dark screen shown. Several seconds later my PS Vita turn off.

I am on 3.65 using enso.

**Comment by SKGleba** [comment]
This sounds like a plugin conflict or incompatible fw type.
 - What are your installed plugins?
 - Are you using any firmware mods such as testkit mod?
 - Are unsafe homebrews enabled in henkaku settings?

**Comment by jasonkhoo87** [comment]
What are your installed plugins?
-download my config from link below. 
https://www.dropbox.com/s/w7oyi38e4w74f96/config.txt?dl=0

Are you using any firmware mods such as testkit mod?
-I am not sure but my firmware is official and used enso. 

Are unsafe homebrews enabled in henkaku settings?
-yes, it is enabled.

**Comment by SKGleba** [comment]
That's alot of plugins, just run VitaDeploy with plugins disabled (hold LT at boot). I will add a mention in the readme.
