### ISSUE TITLE
Offline method not working as expected

### ISSUE THREAD

**Issue by thipeto** [SKGleba/VitaDeploy#16]
I'm debugging the offline method with v1.0.

I put files on ud0 (ud0:PSP2UPDATE/PSP2UPDAT.PUP and ud0:ur0-patch.zip) and checked the "install enso" checkbox, but on Modoru (tiny) screen it appears as "install enso: NO", so I thought it was a bug and proceeded anyway. Enso wasn't installed, it just did the downgrade to 3.65. Even if I copy the "enso.eo" file manually to ud0, the manual install deletes it.

Also, the tutorial here (https://github.com/SKGleba/VitaDeploy) links to this file: "ur0:vd-udl.zip" instead "ud0:ur0-patch.zip", must update:
```
If you do not have network access you can download the packages manually
Put the zip in "ur0:vd-udl.zip", VD will skip OS and tai download
```

Finally, as a offline method it requires to activate wi-fi or an error occurs.

**Comment by SKGleba** [comment]
offline method requires ur0:vd-udl.zip, its not an error.
