### ISSUE TITLE
the HEN and ENSO configration can not effect.

### ISSUE THREAD

**Issue by wangyouqi** [SKGleba/VitaDeploy#18]
Hello, On my psvita2000,when I install 3.65fw from a different OS from ud0:,the HEN and ENSO can not be Installed, but install by download, the HEN and ENSO configration can effect.
![84622](https://user-images.githubusercontent.com/5328033/147823412-168f102f-ceb2-49e3-825f-569faed5c2ea.jpg)

**Comment by SKGleba** [comment]
so to be clear: with a local pup the enso/tai doesnt install? it should but i will recheck
