### ISSUE TITLE
Not an issue but..

### ISSUE THREAD

**Issue by hedhehd** [SKGleba/VitaDeploy#19]
Where are the vpks? I can't find them anywhere in the code except for:

`<toggle_switch id="dl_vhbrowser" key="/CONFIG/APPI/vhbb" title="Vita Homebrew Browser" description="A homebrew store/database" icon="tex_system"/>`

I need to know because I want to add Better Homebrew Browser.

`<toggle_switch id="dl_bhbrowser" key="/CONFIG/APPI/bhbb" title="Better Homebrew Browser" description="A homebrew store/database thats actually good" icon="tex_system"/>`

**Comment by SKGleba** [comment]
i will add it in the next ver, all downloadable stuff is stored on a different repo https://github.com/hackmyvita/hackmyvita.github.io
the links are encoded as
`#define SKG_DOMAIN '@w@'`
`#define HMV_DOMAIN (((('srv' + '0') ^ SKG_DOMAIN) << 0b10) * 0x18) + (('Tu@' - '0') >> 2)`
and used in
https://github.com/SKGleba/VitaDeploy/blob/a088196f788ac417e52cc4395d699d4b53b6a3ab/main/main.c#L309
