### ISSUE TITLE
Issue with vitadeploy as near app

### ISSUE THREAD

**Issue by ACViper** [SKGleba/VitaDeploy#2]
When I try to open Vitashell bubble it now says "insert a ps vita card that contains this application." Is there a way to get the original near app?

**Comment by VictorGamer072YT** [comment]
To get the near app back, just reinstall the firmware.

**Comment by SKGleba** [comment]
uhh i cant replicate but i will look into it

**Comment by nandolawson** [comment]
That would be a way better method than reinstalling the whole firmware. Nice suggestion imo.

**Comment by SKGleba** [comment]
Added in v1.1
