### ISSUE TITLE
Add AutoPlugin 2 to VitaDeploy

### ISSUE THREAD

**Issue by nandolawson** [SKGleba/VitaDeploy#21]
Hey ^^

Title says pretty much everything. It would be cool to have all homebrew tools in one app and AutoPlugin is the last one for me that isn't built into VitaDeploy.

**Comment by rxchiie** [comment]
using autoplugin in general is a bad idea. people have experienced bricked vitas after using autoplugin.

**Comment by hedhehd** [comment]
> using autoplugin in general is a bad idea. people have experienced bricked vitas after using autoplugin.

Hmm lucky for me tho.

**Comment by nandolawson** [comment]
Why would AutoPlugin cause bricks? It was recommended in vita.hacks.guide.

**Comment by hedhehd** [comment]
Yeah like, that doesn't make any sense.

**Comment by rxchiie** [comment]
> Why would AutoPlugin cause bricks? It was even recommended in vita.hacks.guide.

because autoplugin modifies configuration files. and like all automatic software, things go wrong, but AP is just not optimised for such tasks. plus, some plugins require extra installation outside of just dropping a plugin file in the tai folder. AP does not do that.

**Comment by nandolawson** [comment]
Even now there are some tools included in VitaDeploy that also modify configs and system files. Registry Editor and even VitaShell are examples which could theoretically result into a brick. I never had any problems with AutoPlugin and I have used it a lot. Even if something goes wrong, you can disable all plugins at boot and AutoPlugin is unable to change anything besides plugin stuff.

**Comment by rxchiie** [comment]
> Even now there are some tools included in VitaDeploy that also modify configs and system files. Registry Editor and even VitaShell are examples which could theoretically result into a brick. I never had any problems with AutoPlugin and I have used it a lot. Even if something goes wrong, you can disable all plugins at boot and AutoPlugin is unable to change anything besides plugin stuff.

there are literal people complaining about AP bricking their vitas. it's the statistics - everything i said wasn't something i just thought of lol

**Comment by nandolawson** [comment]
Sorry, I never heard of that. Could you give us some examples of people who bricked their Vitas with AP? Because if it is true, it would really be a bad idea to add it.

**Comment by NeonLightning** [comment]
i help on one of the main vita discords and i've personally seen it a few times and alot of softbricks.

**Comment by nandolawson** [comment]
Really weird. AutoPlugin runs stable for many people. Are there cases of softbricks with recent versions?

**Comment by NeonLightning** [comment]
most of it is user error but really easily

**Comment by SKGleba** [comment]
Added in v1.1
