### ISSUE TITLE
used Create an internal memory card option but it messed up

### ISSUE THREAD

**Issue by jcmolero** [SKGleba/VitaDeploy#22]
I used the Create an internal memory card option to make 100MB in the internal memory in the phat psvita, then I decided to restore it to normal thinking of using the default 1xxx option, it made some chantges in the psvita card but in the next reboot it keeps asking to formar the psvita card, without sucess, tried to format in options then in recovery mode, no effect, keeps asking again and again in each reboot, I'm trapped in 3.73 without any chance of getting the card working again, help please!

**Comment by SKGleba** [comment]
weird, imcunlock has checks built-in. so either a faulty memcard or you inserted it post-boot. anyways, its an imcunlock issue.

**Comment by jcmolero** [comment]
The psvita memory is good because it allowed formatting from another psvita, I took mine to service and tech said the nand rendered to a irrecoverable state so required to change the whole board for getting my psvita working again
