### ISSUE TITLE
[Feature Request] Include plugins pack for adrenaline

### ISSUE THREAD

**Issue by NeonLightning** [SKGleba/VitaDeploy#25]
I've been thinking this is a really good pack for adrenaline and would really cut down on the adrenaline modding questions.
[Adrenaline eCFW Plugins & Utilities Pack](https://www.reddit.com/r/vitahacks/comments/6hyo42/release_adrenaline_ecfw_plugins_utilities_pack/)

**Comment by SKGleba** [comment]
Add it to vitadb, wont do.
