### ISSUE TITLE
Vdep desinstalação?

### ISSUE THREAD

**Issue by Maskmanda** [SKGleba/VitaDeploy#26]
Caixa de ferramentas não tem opção de desinstalar!
Baixei e instalei apenas para teste mas não tem como remover e nunca nem vou usar! E não sei onde está alocado ajuda quero remover este ícone 
![16517519068018524145705032812644](https://user-images.githubusercontent.com/104987291/166918768-b21b318a-6078-4680-af1b-4208658f99f4.jpg)

**Comment by SKGleba** [comment]
added in v1.1
