### ISSUE TITLE
Sha256 sum mismatch

### ISSUE THREAD

**Issue by DOMO-Dom** [SKGleba/VitaDeploy#29]
The installation progress till 40-50% then error.
3.74 Firmware:
Tool Downloaded: 
h-encore v1.93
VitaDeploy-FHE - May 10
CMS and Qcma installed. Qcma does not let the h-encore run when running - but CMA works well with connecting CMA on vita to pc

![image](https://user-images.githubusercontent.com/59057047/202409741-23a8e721-2194-484f-9baa-b92a86dbb4e9.png)

**Comment by SKGleba** [comment]
use henlo : visit deploy.psp2.dev using the vita's web browser
