### ISSUE TITLE
`Yamt` plugin enabled by default

### ISSUE THREAD

**Issue by Ericvf** [SKGleba/VitaDeploy#9]
When following the `vita hacking guide` as mentioned on the release page, I've found that VitaDeploy will by default enable the `Yamt` plugin. This caused game cards to not be recognized on my console. 

Since I don't own a `sd2vita` adapter I have skipped that section as instructed. The guide does not mention having to disable the plugin for _default_ behavior. 

To fix it I had to manually disable the `Yamt` plugin via `Settings > Devices` and reboot the console. A good solution would be to have this disabled by default, but I am not sure if that is feasible to achieve. Another option would be to add this to the guide.

**Comment by SKGleba** [comment]
good idea!
